import styles from '../../styles/Home.module.css';

export default function Content() {
  return(
    <div className={styles.container} style={{backgroundColor: "#121212"}}>
      <h2 className={styles.contentheading}>Open Individualism</h2>
      <div className={styles.contentbody}>
        <div className={styles.contenttext}>
          Open Individualism is a philosophical theory proposing that there exists a single entity of consciousness which projects through all conscious organisms within the universe. I am you. You are me. We are us. As such with all theory bordering religion there exist large portions of this idea open to interpretation, yet I will do my best to put forward my interpretations, comparisons, and conclusions. 
          <h3 className={styles.contentheader}>Identity</h3>
          Firstly to begin dissecting this idea for understanding we need to recognize the plane on which we are establishing a connected identity. I separate identity and being into 3 levels: Consciousness &gt; Ego &gt; Physical. The upper level acts as a driving force for the level below it. Changes in a lower lever can be interpreted by a higher level, but projection is unidirectional downstream. Physical can be defined simply as your body and the physical actions which you conduct. Ego is the primary sense of self-identity we have when operating on a day to day basis. Ego is the construct which we created for ourselves through our experiences on earth, detailing our desires, values, morals, and opinions that make us ourselves. Our own ego is what drives our phyical, for example if we believe ourselves to be a musician we may take action to physically create music. Changes to our Physicals cannot directly shape the Ego, no one can do anything physical to you that would directly change your identity, though again physical actions can be interpreted by the Ego allowing it to shape itself based on those interpretations. Beyond the Ego, the driving force behind it would be the Consciousness. The consciousness can be recognized through J. Krishnamurti's phrase: "The Observer is Not the Observed." Essentially stating that because you can step back to watch your thoughts arise and fade, and then make additional judgements on whether to further explore those thoughts within the ego, the "watcher" (or self) cannot be the thought itself. This is the level at which open individualism establishes everyone as being of one. 
          <h3 className={styles.contentheader}>Consciousness Self</h3>
          To further explore the Consciousness level we can consider the following:<br></br>
          Imagine you underwent a brain transplant into a new body completely reshaping your Physical, would you still consider your Ego in that different body to be you?<br></br>
          Up one level we can ask ourselves: if molecules from the egg that created you were changed, you would enter this world both with a completely different Ego and Physical as a result of downstream chemical alterations - would that still be you even if you developed entirely different views as a result of the change?<br></br>
          If we arrive at yes to both of these questions we ultimately propose a higher consciousness level as being the truest form of self.
          Before we get into Consciousness as one, I want to touch upon where open individualism and Buddhism diverge. While Buddhism and open individualism both reject the Ego as the true form of self and reflect on interconnectedness, the metaphysical beliefs of buddhism extend into the concept of empty individualism, rejecting a self at all. Buddhism puts forth that people and things are comprised of "skandhas", or aggregates, which are forms both physical (Rupa) and conceptual (Vendana) that interact to form a temporary Ego. No single component holds the self, and the aggregates themselves are temporary and shifting. Open individualism alternatively has a much less explored metaphysical landscape, but the expectation of a consciousness permanence across all of time and space is implicit. I like to conceptualize the self as a permanent "conscious cloud" that spans the universe though typically the theory specifies no isolated entity or material from which our consciousness derives from, other than being a part of the universe itself.
          <h3 className={styles.contentheader}>Consciousness as One</h3>
          The evidence for all consciousness being from one stems from the idea that if my consciousness was projected through your ego - meaning if I lived your exact experiences as you have experienced them - I would become you at the Ego level, forming the same Ego which you have developed. The suggested reasoning being that we are of the same one Consciousness which would act consistently under the same Ego experience. While this begs the questions then of "who are we?" I find it important to recognize that Identity at the Consciousness level is more abstract than the Ego, often described as lacking character or memories. Whether or not an Ego-like identity exists at this level, I personally wouldn't assert such, yet even without a comprehensible form of personality I would still find believing this higher plane of identity as the driving force behind all conscious organisms as meaningful.
          The primary implications which I derive from this theory go back to this idea - If my Consciousness experienced your experiences and Ego I would develop your Ego - and therefore arrive at all of your proposed values, thoughts, and ideas. This lights a spark of validity to all actions and ideas of the people around you, suggesting under their experience you would formulate the same conclusions and decisions. Ultimately, that line of thinking encourages one to be more open to exploring the possibility of understanding others' decisions even if they sharply contrast from the morals and values held by your current ego. Many people would reject this concept under the false belief that a baseline understanding implies tolerance or acceptance of those decisions, however this is not the case. If one can accept that they themself can be gravely misguided, deceived, and allured it is digestible to extend ones perceived natural faults to others as we should our virtues.  
          Furthermore, and potentially most rewardingly, aligning the self to such as scope reframes the question of self, "Who am I", to not only encapsulate the examination about our own Ego but the Ego of everyone around us. While I continue shaping my beliefs and considering alternate philosophies, experiencing the world for now in this view I find to be fulfilling, unifying, and enlightening.<br></br>
          Although I do not expect this theory to be largely accepted, I invite you to be more open to the consideration;<br></br> In the act of observing others, we may recognize ourselves.
        </div>
      </div>
    </div>
  )
}